# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] || 60 %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 5432 %>

development:
  <<: *default
  database: portfolio_website_development
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: portfolio_website_test
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgresql://portfloio_user:b2nESufraHPE0DvJF7puW7fakXd86yUw@dpg-d2a5kn95pdvs73adfsag-a/portfloio" %>

cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgresql://portfloio_user:b2nESufraHPE0DvJF7puW7fakXd86yUw@dpg-d2a5kn95pdvs73adfsag-a/portfloio" %>


queue:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgresql://portfloio_user:b2nESufraHPE0DvJF7puW7fakXd86yUw@dpg-d2a5kn95pdvs73adfsag-a/portfloio" %>
  

cache:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgresql://portfloio_user:b2nESufraHPE0DvJF7puW7fakXd86yUw@dpg-d2a5kn95pdvs73adfsag-a/portfloio" %>